services:
  # Servicio del Backend (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=files
    depends_on:
      - mongodb
      - minio
    networks:
      - app-network

  # Servicio del Frontend (SvelteKit)
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  # Servicio de la Base de Datos (MongoDB)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Servicio de Almacenamiento de Objetos (MinIO)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

# Red para la comunicación entre servicios
networks:
  app-network:
    driver: bridge

# Volúmenes para la persistencia de datos (Docker managed volumes for CI)
volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local
